/**
 * @fileoverview Differential test: VAXFloat vs. the real Open SIMH microvax3900
 * @author Jeff Parsons <Jeff@pcjs.org>
 * @copyright © 2012-2026 Jeff Parsons
 * @license MIT <https://www.pcjs.org/LICENSE.txt>
 *
 * This file is part of PCjs, a computer emulation software project at <https://www.pcjs.org>.
 *
 * WHAT THIS IS
 * ------------
 * A differential test of machines/dec/vax/modules/v2/fpa.js -- VAX F, D and G floating point --
 * against a REAL, EXECUTED Open SIMH microvax3900.  No fixtures, no golden files: every run
 * builds a command stream, launches the simulator, and compares its actual output.  If the
 * binary is missing, or is missing patch 0004, the test FAILS -- it never degrades into
 * self-comparison.
 *
 *      machines/dec/vax/tests/simh/build.sh $TMPDIR/pcjs-vax-simh-fp
 *      node machines/dec/vax/tests/fpadiff.js --selfcheck
 *      node machines/dec/vax/tests/fpadiff.js
 *
 * Options:
 *      --simh PATH     the microvax3900 to grade against
 *      --cases N       exerciser cases (default 60000; below 40000 FAILS, it does not scale down)
 *      --seed N        RNG seed
 *      --trace FILE    reuse an existing EHKAA capture instead of running SIMH for it
 *      --ehkaa PATH    the EHKAA diagnostic image
 *      --skip-ehkaa    run only the randomized phases
 *      --selfcheck     run the mutation suite instead of the full differential
 *
 * WHY THE ORACLE IS SHAPED LIKE THIS
 * ----------------------------------
 * Floating point is not observable from outside the machine either.  A program that computes
 * with it stores the answer somewhere, but it never presents the simulator with a reserved
 * operand, an exact rounding tie, or an exponent one step past overflow -- and those are exactly
 * the cases a port gets wrong.  Patch 0004 adds one thing and nothing else:
 *
 *      SHOW CPU FPOP=opc:psl:cc:spec:rn:va:d0:d1:n:o0:o1:...
 *
 * which runs ONE floating instruction -- the case body copied verbatim out of sim_instr()'s
 * dispatch, so the arithmetic is the real op_* routines from vax_fpa.c, the condition codes are
 * the real macros from vax_defs.h, and the store is the real WRITE_B/W/L/Q macros -- and prints
 * the condition codes, the trap request, the destination registers, or the abort.  It is
 * additive; the simulator's own EHKAA self-test passes with it applied.
 *
 * THREE PHASES
 * ------------
 *   EXERCISER   Randomized, but NOT uniform -- see below.  Every in-scope opcode, both
 *               destination kinds, PSL<FU> and PSL<IV> both ways, and operand pools built out of
 *               the classes that actually break floating point ports.
 *
 *   EHKAA       The DEC EHKAA hardware core diagnostic run to its PASS halt.  Every F/D/G
 *               instruction it executes is lifted out of the instruction history -- the opcode
 *               from the `IBYT` line, the resolved operand queue from the `OPND` line -- and
 *               replayed.  This is the real-workload phase: the opcode mix and the operand
 *               values are a real program's, not a generator's.  It grades two ways: against
 *               the result the diagnostic's own execution printed in the history record, and
 *               against a FPOP replay of the same inputs, which additionally grades condition
 *               codes and faults.
 *
 *   QUADSTORE   WRITE_Q's cross-page access probe, with memory management ON.  A quadword
 *               floating store whose second page is inaccessible must leave NOTHING behind and
 *               must report the fault for the FIRST page when both pages are bad.  That is the
 *               one part of the store path that a MAPEN-off phase cannot reach.
 *
 * WHY A UNIFORM RANDOM POOL WOULD PROVE NOTHING
 * ---------------------------------------------
 * pcjsvax-cd6 learned this the expensive way: a uniform pool left 97% of its comparisons trivial
 * and let a deliberately broken boundary survive 150,000 operations.  Floating point is worse.
 * Two random 32-bit words are, with overwhelming probability, two ordinary numbers of wildly
 * different magnitude; adding them returns the larger one unchanged, and the run "passes" without
 * ever having rounded, normalized, overflowed or faulted.  So the operands here are generated by
 * CLASS, and the run FAILS if any class falls below its floor:
 *
 *   zero              a true zero operand (exponent 0, sign 0)
 *   resop             a RESERVED OPERAND (exponent 0, sign 1).  DEC floating point has no
 *                     negative zero and no NaN: that bit pattern is a fault, and the exact
 *                     pattern 0x00008000 -- what an IEEE port would produce for -0.0 -- is
 *                     generated deliberately and counted separately as `negzero`.
 *   tinyexp           an operand at the bottom of the exponent range (1..4).  DEC floating point
 *                     has no denormals either; the analogous edge is the exponent-0 cliff, so
 *                     the classes that matter are this one, `underflow` and `resop`.
 *   maxexp            an operand at the top of the exponent range
 *   roundTie          the second operand scaled so its leading bit lands EXACTLY on the round
 *                     bit of the result (exponent difference 24 for F, 56 for D, 53 for G), plus
 *                     the two neighbouring differences.  These are the ties; nothing else is.
 *   cancellation      near-equal magnitudes of opposite sign, so the effective subtraction
 *                     cancels the top k bits and norm() has to renormalize a long way
 *   ediff*            exponent differences straddling the shift-count branches in dp_lsh/dp_rsh
 *                     (0, 1..31, 32..63, >= 64), which are where a JavaScript port dies: `x << 32`
 *                     is `x` in JavaScript, not 0
 *   overflow          the result exponent passes the format maximum -> arithmetic fault
 *   underflow         the result exponent falls to 0 or below -> zero, or a fault when PSL<FU>
 *   divzero           a zero divisor -> arithmetic fault
 *   intovf            float-to-integer conversion out of range -> V set, and a TRAP when PSL<IV>
 *
 * NOTHING MAY BE SILENTLY DROPPED
 * -------------------------------
 * pcjsvax-8c0 lost 21% of its cases invisibly.  Every case emitted here must produce exactly one
 * FPOP line; the count is checked, and any case whose line is missing is reported BY INDEX with
 * its opcode and operands.  The EHKAA phase counts the F/D/G records it found against the
 * comparisons it performed and fails on any difference.
 *
 * SELF-CHECK
 * ----------
 * --selfcheck re-runs a short pass with a deliberate defect injected into the SHIPPED code path
 * and fails if the differential does not catch it.  The defects are listed in MUTATIONS; the
 * first two are rounding defects and the third is a normalization defect, because those are what
 * this item exists to get right.
 */

import fs from "fs";
import os from "os";
import path from "path";
import { execFileSync } from "child_process";
import { fileURLToPath } from "url";

import BusVAX from "../modules/v2/bus.js";
import MemoryVAX from "../modules/v2/memory.js";
import MMUVAX from "../modules/v2/mmu.js";
import { VAXFault, VAXFAULT } from "../modules/v2/decode.js";
import VAXFloat, { OPC, FPSIGN, PSW_FU, PSW_IV, ABORT_ARITH,
    FLT_OVRFLO, FLT_DIVZRO, FLT_UNDFLO, WORDSWAP } from "../modules/v2/fpa.js";
/*
 * The dp_* helpers applyMutation()'s addNoCarryNorm copy needs.  Imported from fpa.js rather
 * than reimplemented, so that copy differs from the shipped vaxFadd() in exactly one place.
 */
import { dpCmp as dpCmpT, dpAdd as dpAddT, dpSub as dpSubT, dpRsh as dpRshT,
    dpRshS as dpRshST, dpNeg as dpNegT, dpLsh as dpLshT } from "../modules/v2/fpa.js";
import { VAX } from "../modules/v2/defines.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../../..");

const MEMSIZE       = 0x01000000;       // 16MB, SIMH's microvax3900 default

const DEFAULT_CASES = 60000;
const MIN_CASES     = 40000;

/*
 * The destination buffer used by memory-destination cases in the EXERCISER phase, with memory
 * management OFF so a virtual address is a physical address.  16 bytes per case leaves room for
 * a quadword at an unaligned offset without two cases ever touching the same longword, which is
 * what makes the final read-back sweep attributable to a single case.
 */
const DST_BASE      = 0x00800000;
const DST_STRIDE    = 16;
const DST_FILL      = 0xDEADBEEF | 0;

/* ------------------------------------------------------------------------------------------- *
 * The opcode table
 *
 * `srcs` lists the FORMAT of each operand-queue slot the instruction's arithmetic reads, which is
 * what decides how many longwords the case must generate and from which pool.  It is NOT the
 * decode ROM's specifier list: ADDF2 (`RF,MF`) and ADDF3 (`RF,RF,WF`) both hand op_addf() the
 * same opnd[0..1], which is exactly why SIMH shares one case body between them.
 *
 * `dest` is the width the instruction stores, or null for TSTx/CMPx which store nothing.
 * ------------------------------------------------------------------------------------------- */

const OPS = [
    {opc: OPC.TSTF,   name: "TSTF",   srcs: ["F"],           dest: null},
    {opc: OPC.TSTD,   name: "TSTD",   srcs: ["D"],           dest: null},
    {opc: OPC.TSTG,   name: "TSTG",   srcs: ["G"],           dest: null},
    {opc: OPC.MOVF,   name: "MOVF",   srcs: ["F"],           dest: "L"},
    {opc: OPC.MOVD,   name: "MOVD",   srcs: ["D"],           dest: "Q"},
    {opc: OPC.MOVG,   name: "MOVG",   srcs: ["G"],           dest: "Q"},
    {opc: OPC.MNEGF,  name: "MNEGF",  srcs: ["F"],           dest: "L"},
    {opc: OPC.MNEGD,  name: "MNEGD",  srcs: ["D"],           dest: "Q"},
    {opc: OPC.MNEGG,  name: "MNEGG",  srcs: ["G"],           dest: "Q"},
    {opc: OPC.CMPF,   name: "CMPF",   srcs: ["F", "F"],      dest: null},
    {opc: OPC.CMPD,   name: "CMPD",   srcs: ["D", "D"],      dest: null},
    {opc: OPC.CMPG,   name: "CMPG",   srcs: ["G", "G"],      dest: null},

    {opc: OPC.CVTBF,  name: "CVTBF",  srcs: ["b"],           dest: "L"},
    {opc: OPC.CVTWF,  name: "CVTWF",  srcs: ["w"],           dest: "L"},
    {opc: OPC.CVTLF,  name: "CVTLF",  srcs: ["l"],           dest: "L"},
    {opc: OPC.CVTBD,  name: "CVTBD",  srcs: ["b"],           dest: "Q"},
    {opc: OPC.CVTWD,  name: "CVTWD",  srcs: ["w"],           dest: "Q"},
    {opc: OPC.CVTLD,  name: "CVTLD",  srcs: ["l"],           dest: "Q"},
    {opc: OPC.CVTBG,  name: "CVTBG",  srcs: ["b"],           dest: "Q"},
    {opc: OPC.CVTWG,  name: "CVTWG",  srcs: ["w"],           dest: "Q"},
    {opc: OPC.CVTLG,  name: "CVTLG",  srcs: ["l"],           dest: "Q"},

    {opc: OPC.CVTFB,  name: "CVTFB",  srcs: ["F"],           dest: "B"},
    {opc: OPC.CVTDB,  name: "CVTDB",  srcs: ["D"],           dest: "B"},
    {opc: OPC.CVTGB,  name: "CVTGB",  srcs: ["G"],           dest: "B"},
    {opc: OPC.CVTFW,  name: "CVTFW",  srcs: ["F"],           dest: "W"},
    {opc: OPC.CVTDW,  name: "CVTDW",  srcs: ["D"],           dest: "W"},
    {opc: OPC.CVTGW,  name: "CVTGW",  srcs: ["G"],           dest: "W"},
    {opc: OPC.CVTFL,  name: "CVTFL",  srcs: ["F"],           dest: "L"},
    {opc: OPC.CVTDL,  name: "CVTDL",  srcs: ["D"],           dest: "L"},
    {opc: OPC.CVTGL,  name: "CVTGL",  srcs: ["G"],           dest: "L"},
    {opc: OPC.CVTRFL, name: "CVTRFL", srcs: ["F"],           dest: "L"},
    {opc: OPC.CVTRDL, name: "CVTRDL", srcs: ["D"],           dest: "L"},
    {opc: OPC.CVTRGL, name: "CVTRGL", srcs: ["G"],           dest: "L"},

    {opc: OPC.CVTFD,  name: "CVTFD",  srcs: ["F"],           dest: "Q"},
    {opc: OPC.CVTDF,  name: "CVTDF",  srcs: ["D"],           dest: "L"},
    {opc: OPC.CVTFG,  name: "CVTFG",  srcs: ["F"],           dest: "Q"},
    {opc: OPC.CVTGF,  name: "CVTGF",  srcs: ["G"],           dest: "L"},

    {opc: OPC.ADDF2,  name: "ADDF2",  srcs: ["F", "F"],      dest: "L", arith: true},
    {opc: OPC.ADDF3,  name: "ADDF3",  srcs: ["F", "F"],      dest: "L", arith: true},
    {opc: OPC.SUBF2,  name: "SUBF2",  srcs: ["F", "F"],      dest: "L", arith: true},
    {opc: OPC.SUBF3,  name: "SUBF3",  srcs: ["F", "F"],      dest: "L", arith: true},
    {opc: OPC.MULF2,  name: "MULF2",  srcs: ["F", "F"],      dest: "L", arith: true},
    {opc: OPC.MULF3,  name: "MULF3",  srcs: ["F", "F"],      dest: "L", arith: true},
    {opc: OPC.DIVF2,  name: "DIVF2",  srcs: ["F", "F"],      dest: "L", arith: true, div: true},
    {opc: OPC.DIVF3,  name: "DIVF3",  srcs: ["F", "F"],      dest: "L", arith: true, div: true},

    {opc: OPC.ADDD2,  name: "ADDD2",  srcs: ["D", "D"],      dest: "Q", arith: true},
    {opc: OPC.ADDD3,  name: "ADDD3",  srcs: ["D", "D"],      dest: "Q", arith: true},
    {opc: OPC.SUBD2,  name: "SUBD2",  srcs: ["D", "D"],      dest: "Q", arith: true},
    {opc: OPC.SUBD3,  name: "SUBD3",  srcs: ["D", "D"],      dest: "Q", arith: true},
    {opc: OPC.MULD2,  name: "MULD2",  srcs: ["D", "D"],      dest: "Q", arith: true},
    {opc: OPC.MULD3,  name: "MULD3",  srcs: ["D", "D"],      dest: "Q", arith: true},
    {opc: OPC.DIVD2,  name: "DIVD2",  srcs: ["D", "D"],      dest: "Q", arith: true, div: true},
    {opc: OPC.DIVD3,  name: "DIVD3",  srcs: ["D", "D"],      dest: "Q", arith: true, div: true},

    {opc: OPC.ADDG2,  name: "ADDG2",  srcs: ["G", "G"],      dest: "Q", arith: true},
    {opc: OPC.ADDG3,  name: "ADDG3",  srcs: ["G", "G"],      dest: "Q", arith: true},
    {opc: OPC.SUBG2,  name: "SUBG2",  srcs: ["G", "G"],      dest: "Q", arith: true},
    {opc: OPC.SUBG3,  name: "SUBG3",  srcs: ["G", "G"],      dest: "Q", arith: true},
    {opc: OPC.MULG2,  name: "MULG2",  srcs: ["G", "G"],      dest: "Q", arith: true},
    {opc: OPC.MULG3,  name: "MULG3",  srcs: ["G", "G"],      dest: "Q", arith: true},
    {opc: OPC.DIVG2,  name: "DIVG2",  srcs: ["G", "G"],      dest: "Q", arith: true, div: true},
    {opc: OPC.DIVG3,  name: "DIVG3",  srcs: ["G", "G"],      dest: "Q", arith: true, div: true}
];

const OPS_BY_OPC = new Map(OPS.map((o) => [o.opc, o]));

/*
 * Format geometry.  `sig` is the number of SIGNIFICANT bits (hidden bit included), which is the
 * exponent difference at which a second operand's leading bit lands exactly on the round bit --
 * i.e. the exact tie.  `bias` and `maxexp` are the format's; `lw` is how many longwords a value
 * occupies in the operand queue.
 */
const FMT = {
    F: {sig: 24, bias: 0x80,  maxexp: 0xFF,  lw: 1},
    D: {sig: 56, bias: 0x80,  maxexp: 0xFF,  lw: 2},
    G: {sig: 53, bias: 0x400, maxexp: 0x7FF, lw: 2}
};

/* ------------------------------------------------------------------------------------------- *
 * Coverage floors.  Every one of these FAILS the run when it is not met; an undersized run does
 * not quietly pass.  They are stated as absolute counts against the default case count, so
 * --cases below MIN_CASES is rejected outright rather than scaling the floors down with it.
 * ------------------------------------------------------------------------------------------- */

const FLOORS = {
    perOpcode:      120,        // every one of the 61 in-scope opcodes
    zero:           2000,
    resop:          2000,
    negzero:         300,
    tinyexp:        2000,
    maxexp:         2000,
    roundTie:        600,
    roundNear:       600,       // the two exponent differences either side of the tie
    cancellation:   1000,
    ediff0:          800,
    ediff1_31:      2000,
    ediff32_63:      800,
    ediff64:         800,
    overflow:        400,
    underflow:       400,
    underflowFault:  150,       // underflow with PSL<FU> set, which FAULTS instead of returning 0
    divzero:         200,
    intovf:          400,
    intovfTrap:      150,       // integer overflow with PSL<IV> set, which requests a TRAP
    intbound:        400,       // a conversion landing exactly on the integer limit
    resad:            80,       // quadword store to R14/R15
    memDest:        8000,
    regDest:        8000,
    faulted:        3000,
    nonTrivial:     0.60        // fraction of non-faulting cases whose result is neither the
                                // first operand unchanged nor zero
};

const MIN_EHKAA_FP  = 500;      // F/D/G instructions EHKAA is measured to execute (~700)
const MIN_EHKAA_INSITU = 300;   // of those, how many must be graded against the printed result
const MIN_QUAD_CASES   = 400;
const MIN_QUAD_FAULTS  = 120;

/* ------------------------------------------------------------------------------------------- *
 * Small helpers
 * ------------------------------------------------------------------------------------------- */

/**
 * mulberry32(a)
 *
 * A tiny deterministic PRNG, so a failing run is reproducible from its seed alone.
 *
 * @param {number} a
 * @returns {function(): number}
 */
function mulberry32(a)
{
    return function() {
        a |= 0; a = (a + 0x6D2B79F5) | 0;
        let t = Math.imul(a ^ (a >>> 15), 1 | a);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

/**
 * hex(v, digits)
 *
 * @param {number} v
 * @param {number} [digits]
 * @returns {string}
 */
function hex(v, digits)
{
    let s = (v >>> 0).toString(16).toUpperCase();
    return digits? s.padStart(digits, "0") : s;
}

/**
 * rnd32(rng)
 *
 * @param {function(): number} rng
 * @returns {number} int32
 */
function rnd32(rng)
{
    return ((rng() * 0x10000) & 0xFFFF) | (((rng() * 0x10000) & 0xFFFF) << 16);
}

/**
 * pick(rng, a)
 *
 * @param {function(): number} rng
 * @param {Array} a
 * @returns {*}
 */
function pick(rng, a)
{
    return a[(rng() * a.length) | 0];
}

/**
 * rndInt(rng, lo, hi)  -- inclusive
 *
 * @param {function(): number} rng
 * @param {number} lo
 * @param {number} hi
 * @returns {number}
 */
function rndInt(rng, lo, hi)
{
    return lo + ((rng() * (hi - lo + 1)) | 0);
}

/* ------------------------------------------------------------------------------------------- *
 * Building floating point values
 *
 * All three formats store the fraction WORD-SWAPPED, which is why none of these is a simple
 * shift-and-or.  The layout is derived from vax_fpa.c's unpack routines, not from the
 * architecture manual: unpackd() forms its 64-bit fraction as
 * [WORDSWAP(hi & FD_FRACL | FD_HB)][WORDSWAP(lo)], so the fraction's most significant bits are
 * the LOW word of the LOW longword.
 * ------------------------------------------------------------------------------------------- */

/**
 * mkF(sign, exp, frac)
 *
 * @param {number} sign 0 or 1
 * @param {number} exp  0..0xFF
 * @param {number} frac 23-bit fraction, most significant bit at 22
 * @returns {Array.<number>} one longword
 */
function mkF(sign, exp, frac)
{
    frac = frac & 0x7FFFFF;
    let lw = (sign? FPSIGN : 0) | ((exp & 0xFF) << 7) | ((frac >>> 16) & 0x7F) |
        ((frac & 0xFFFF) << 16);
    return [lw | 0];
}

/**
 * mkD(sign, exp, fracHi, fracLo)
 *
 * @param {number} sign
 * @param {number} exp   0..0xFF
 * @param {number} fracHi fraction bits 54..32 (23 bits)
 * @param {number} fracLo fraction bits 31..0
 * @returns {Array.<number>} two longwords, low first
 */
function mkD(sign, exp, fracHi, fracLo)
{
    fracHi = fracHi & 0x7FFFFF;
    let hi = (sign? FPSIGN : 0) | ((exp & 0xFF) << 7) | ((fracHi >>> 16) & 0x7F) |
        ((fracHi & 0xFFFF) << 16);
    return [hi | 0, WORDSWAP(fracLo) | 0];
}

/**
 * mkG(sign, exp, fracHi, fracLo)
 *
 * @param {number} sign
 * @param {number} exp    0..0x7FF
 * @param {number} fracHi fraction bits 51..32 (20 bits)
 * @param {number} fracLo fraction bits 31..0
 * @returns {Array.<number>} two longwords, low first
 */
function mkG(sign, exp, fracHi, fracLo)
{
    fracHi = fracHi & 0xFFFFF;
    let hi = (sign? FPSIGN : 0) | ((exp & 0x7FF) << 4) | ((fracHi >>> 16) & 0xF) |
        ((fracHi & 0xFFFF) << 16);
    return [hi | 0, WORDSWAP(fracLo) | 0];
}

/**
 * mk(fmt, sign, exp, fracHi, fracLo)
 *
 * @param {string} fmt "F", "D" or "G"
 * @param {number} sign
 * @param {number} exp
 * @param {number} fracHi
 * @param {number} fracLo
 * @returns {Array.<number>}
 */
function mk(fmt, sign, exp, fracHi, fracLo)
{
    if (fmt == "F") return mkF(sign, exp, fracHi);
    if (fmt == "D") return mkD(sign, exp, fracHi, fracLo);
    return mkG(sign, exp, fracHi, fracLo);
}

/**
 * fromIntExact(fmt, n, halfDir)
 *
 * The encoding of `n + halfDir/2` in `fmt`, or null when that value is not EXACTLY representable
 * there.  Exactness is the whole point: this exists to put a float-to-integer conversion on the
 * precise boundary where `maxv[lnt] + (sign? 1 : 0)` decides between a clean answer and integer
 * overflow, and "near 2147483647" is not the same test as "exactly 2147483647".
 *
 * BigInt is used deliberately -- this is test scaffolding, not the shipped path, and getting the
 * 55-bit D fraction right with doubles would be its own bug.
 *
 * @param {string} fmt
 * @param {number} n
 * @param {number} halfDir  -1, 0 or +1: subtract, ignore, or add one half
 * @returns {?Array.<number>}
 */
function fromIntExact(fmt, n, halfDir)
{
    let f = FMT[fmt];
    /* work in units of one half, then take the exponent back down by one */
    let scaled = BigInt(2 * n + halfDir);
    if (scaled == 0n) return mk(fmt, 0, 0, 0, 0);
    let neg = scaled < 0n;
    let a = neg? -scaled : scaled;
    let bits = a.toString(2).length;
    if (bits > f.sig) return null;                      // more significant bits than the format has
    let e = bits - 1;
    let frac = (a << BigInt(f.sig - 1 - e)) & ((1n << BigInt(f.sig - 1)) - 1n);
    let exp = f.bias + e + 1 - 1;                       // +1 for the hidden bit, -1 for the halving
    if (exp < 1 || exp > f.maxexp) return null;
    let fracHi = (fmt == "F")? Number(frac) : Number(frac >> 32n);
    let fracLo = (fmt == "F")? 0 : Number(frac & 0xFFFFFFFFn);
    return mk(fmt, neg? 1 : 0, exp, fracHi, fracLo);
}

/**
 * getExp(fmt, v)
 *
 * @param {string} fmt
 * @param {Array.<number>} v
 * @returns {number} biased exponent
 */
function getExp(fmt, v)
{
    return (fmt == "G")? ((v[0] >>> 4) & 0x7FF) : ((v[0] >>> 7) & 0xFF);
}

/**
 * getSign(fmt, v)
 *
 * @param {string} fmt
 * @param {Array.<number>} v
 * @returns {number} 0 or 1
 */
function getSign(fmt, v)
{
    return (v[0] & FPSIGN)? 1 : 0;
}

/*
 * Fraction patterns.  The all-ones and all-but-one-bit patterns matter far more than random
 * ones: they are what carries out of the round, and what leaves a normalization exactly one
 * shift short.
 */
const FRAC_PATTERNS = ["zero", "ones", "high", "low", "lowbit", "highbit", "alt", "random"];

/**
 * mkFrac(rng, bits, pat)
 *
 * @param {function(): number} rng
 * @param {number} bits width of the field
 * @param {string} pat
 * @returns {number}
 */
function mkFrac(rng, bits, pat)
{
    let all = (bits >= 32)? 0xFFFFFFFF : ((1 << bits) - 1);
    switch (pat) {
    case "zero":    return 0;
    case "ones":    return all >>> 0;
    case "high":    return (all & ~(all >>> 4)) >>> 0;
    case "low":     return (all >>> 4) >>> 0;
    case "lowbit":  return 1;
    case "highbit": return (bits >= 32)? 0x80000000 : (1 << (bits - 1));
    case "alt":     return (all & 0xAAAAAAAA) >>> 0;
    default:        return (rnd32(rng) & all) >>> 0;
    }
}

/**
 * genValue(rng, fmt, cls, ctx)
 *
 * Generate one operand of `fmt` belonging to edge class `cls`.  `ctx` accumulates the class
 * labels this value contributes, which is what the coverage floors count.
 *
 * @param {function(): number} rng
 * @param {string} fmt
 * @param {string} cls
 * @param {Set.<string>} ctx
 * @returns {Array.<number>}
 */
function genValue(rng, fmt, cls, ctx)
{
    let f = FMT[fmt];
    let sign = (rng() < 0.5)? 1 : 0;
    let pat = pick(rng, FRAC_PATTERNS);
    let fracHi = mkFrac(rng, (fmt == "F")? 23 : (fmt == "D")? 23 : 20, pat);
    let fracLo = mkFrac(rng, 32, pick(rng, FRAC_PATTERNS));

    switch (cls) {
    case "zero":
        ctx.add("zero");
        return mk(fmt, 0, 0, 0, 0);
    case "resop":
        ctx.add("resop");
        if (rng() < 0.3) {
            ctx.add("negzero");                         // the exact IEEE "-0.0" bit pattern
            return mk(fmt, 1, 0, 0, 0);
        }
        return mk(fmt, 1, 0, fracHi, fracLo);
    case "tinyexp":
        ctx.add("tinyexp");
        return mk(fmt, sign, rndInt(rng, 1, 4), fracHi, fracLo);
    case "maxexp":
        ctx.add("maxexp");
        return mk(fmt, sign, rndInt(rng, f.maxexp - 3, f.maxexp), fracHi, fracLo);
    case "unit":
        return mk(fmt, sign, f.bias + rndInt(rng, -3, 3), fracHi, fracLo);
    default:
        return mk(fmt, sign, rndInt(rng, 1, f.maxexp), fracHi, fracLo);
    }
}

/* ------------------------------------------------------------------------------------------- *
 * Case generation
 * ------------------------------------------------------------------------------------------- */

/*
 * Edge classes for a whole CASE (as opposed to a single operand).  The pair classes exist
 * because the interesting behaviour of add, subtract, multiply and divide is a property of the
 * RELATIONSHIP between the operands, and no per-operand pool can produce it.
 */
const CASE_CLASSES = [
    ["plain",        14],
    ["zero",          8],
    ["resop",         8],
    ["tinyexp",       7],
    ["maxexp",        7],
    ["roundTie",     10],       // exponent difference == sig, sig-1, sig+1
    ["cancellation",  9],
    ["ediff",        10],       // exponent differences straddling the dp_lsh/dp_rsh branches
    ["overflow",      6],
    ["underflow",     6],
    ["divzero",       4],
    ["intovf",        6],
    ["sameval",       5],       // both operands identical: exact cancellation, exact ratio
    ["intbound",      8]        // float-to-integer conversion landing EXACTLY on the limit
];

/*
 * The integer values a float-to-integer conversion must get exactly right, by destination width.
 * The limit is asymmetric -- op_cvtfdgi() compares against `maxv[lnt] + (a.sign? 1 : 0)` -- so
 * -128, -32768 and -2147483648 do NOT overflow while +128, +32768 and +2147483648 do, and the
 * pair either side of each is what proves a port implements that and not `abs(x) > max`.
 */
const INT_BOUNDS = {
    B: [126, 127, 128, 129, -127, -128, -129, 0, 1, -1],
    W: [32766, 32767, 32768, 32769, -32767, -32768, -32769, 0, 1, -1],
    L: [2147483646, 2147483647, 2147483648, 2147483649,
        -2147483647, -2147483648, -2147483649, 65536, -65536, 1]
};

const EDIFFS = [0, 1, 2, 7, 8, 15, 16, 23, 24, 25, 31, 32, 33, 47, 52, 53, 55, 56, 57,
                63, 64, 65, 80, 127, 200, 600, 1500];

/**
 * genSrcs(rng, op, cls, ctx)
 *
 * Produce the operand-queue longwords for one case.  Returns null when the class cannot be
 * applied to this opcode (e.g. `divzero` for a non-divide), so the caller can re-roll.
 *
 * @param {function(): number} rng
 * @param {Object} op
 * @param {string} cls
 * @param {Set.<string>} ctx
 * @returns {?Array.<number>}
 */
function genSrcs(rng, op, cls, ctx)
{
    let srcs = op.srcs;
    let fmt = srcs[0];

    /* integer sources: CVTBF / CVTWD / CVTLG and friends */
    if (fmt == "b" || fmt == "w" || fmt == "l") {
        let v;
        if (fmt == "b") v = rndInt(rng, 0, 0xFF);
        else if (fmt == "w") v = rndInt(rng, 0, 0xFFFF);
        else {
            /*
             * The value that must survive: -2147483648 negates to itself, and `val & LMASK` is
             * what makes op_cvtifdg() cope.  A uniform pool hits it with probability 2^-32.
             */
            v = pick(rng, [0, 1, -1, 0x7FFFFFFF, 0x80000000 | 0, 0x40000000, -0x40000000,
                rnd32(rng), rnd32(rng), rndInt(rng, -1000, 1000)]) | 0;
        }
        if (v == 0) ctx.add("zero");
        return [v | 0];
    }

    let f = FMT[fmt];
    let nsrc = srcs.length;

    /* single-source instructions: MOVx, MNEGx, TSTx, CVTxB/W/L, CVTFD/DF/FG/GF */
    if (nsrc == 1) {
        if (cls == "intbound") {
            /*
             * Only the float-to-integer conversions have an integer limit to sit on.  The half
             * variants matter for CVTRxL specifically: 2147483647.5 rounds UP past the limit
             * while 2147483647.0 does not, and truncating CVTxL disagrees with both.
             */
            if (!INT_BOUNDS[op.dest]) return null;
            let n = pick(rng, INT_BOUNDS[op.dest]);
            let v = fromIntExact(fmt, n, (rng() < 0.4)? pick(rng, [-1, 1]) : 0);
            if (!v) return null;                        // not exact in this format; re-roll
            ctx.add("intbound");
            return v;
        }
        let vcls = cls;
        if (cls == "roundTie" || cls == "cancellation" || cls == "ediff" ||
            cls == "divzero" || cls == "sameval") vcls = "plain";
        if (cls == "overflow" || cls == "intovf") {
            /*
             * CVTFB/W/L overflow needs a large magnitude; CVTFG/CVTDF/CVTGF overflow needs an
             * exponent that will not fit the DESTINATION format once rebiased.
             */
            ctx.add(cls == "intovf"? "intovf" : "overflow");
            return mk(fmt, (rng() < 0.5)? 1 : 0, rndInt(rng, f.bias + 30, f.maxexp),
                mkFrac(rng, (fmt == "F")? 23 : (fmt == "D")? 23 : 20, pick(rng, FRAC_PATTERNS)),
                mkFrac(rng, 32, pick(rng, FRAC_PATTERNS)));
        }
        if (cls == "underflow") {
            ctx.add("tinyexp");
            return mk(fmt, (rng() < 0.5)? 1 : 0, rndInt(rng, 1, 3),
                mkFrac(rng, (fmt == "F")? 23 : (fmt == "D")? 23 : 20, pick(rng, FRAC_PATTERNS)),
                mkFrac(rng, 32, pick(rng, FRAC_PATTERNS)));
        }
        return genValue(rng, fmt, vcls, ctx);
    }

    /* two-source instructions: CMPx, ADDx, SUBx, MULx, DIVx */
    let a, b;
    switch (cls) {

    case "roundTie": {
        /*
         * THE tie.  `a` has exponent E; `b` has exponent E - sig, so b's leading (hidden) bit
         * lands exactly on the round bit of a + b.  sig-1 rounds up cleanly, sig+1 down.  The
         * sticky bits below are varied, because a tie with anything below it is not a tie.
         */
        let d = pick(rng, [f.sig - 1, f.sig, f.sig, f.sig + 1]);
        ctx.add(d == f.sig? "roundTie" : "roundNear");
        ctx.add("ediff1_31");
        let ea = rndInt(rng, f.bias + 4, f.maxexp - 4);
        let eb = ea - d;
        if (eb < 1) { eb = 1; }
        let sticky = (rng() < 0.5);
        a = mk(fmt, 0, ea, mkFrac(rng, (fmt == "F")? 23 : (fmt == "D")? 23 : 20,
            pick(rng, ["zero", "ones", "lowbit", "random"])), mkFrac(rng, 32, "random"));
        b = mk(fmt, (rng() < 0.35)? 1 : 0, eb,
            sticky? mkFrac(rng, (fmt == "F")? 23 : (fmt == "D")? 23 : 20, "random") : 0,
            sticky? mkFrac(rng, 32, "random") : 0);
        break;
    }

    case "cancellation": {
        /*
         * Near-equal magnitudes of opposite sign: the effective subtract cancels the top k bits
         * and norm() has to shift a long way back.  k is swept across the normmask/normtab
         * binary-search boundaries in norm(), which is where a broken shift table hides.
         */
        ctx.add("cancellation");
        ctx.add("ediff0");
        let e = rndInt(rng, f.bias, f.maxexp - 2);
        let k = pick(rng, [0, 1, 2, 3, 4, 7, 8, 15, 16, 17, 23, 31, 32, 33, 40, 51, 52, 55]);
        let sgn = (rng() < 0.5)? 1 : 0;
        let hiBits = (fmt == "G")? 20 : 23;
        let fh = mkFrac(rng, hiBits, "random");
        let fl = mkFrac(rng, 32, "random");
        a = mk(fmt, sgn, e, fh, fl);
        /* flip exactly one low bit k places up, so the difference is 2^k ulp */
        let gh = fh, gl = fl;
        if (k < 32) gl = (fl ^ (1 << k)) >>> 0;
        else gh = (fh ^ (1 << (k - 32))) >>> 0;
        b = mk(fmt, sgn ^ 1, e, gh, gl);
        break;
    }

    case "ediff": {
        let d = pick(rng, EDIFFS);
        if (d == 0) ctx.add("ediff0");
        else if (d < 32) ctx.add("ediff1_31");
        else if (d < 64) ctx.add("ediff32_63");
        else ctx.add("ediff64");
        let ea = rndInt(rng, Math.min(f.maxexp - 2, d + 2), f.maxexp - 1);
        let eb = Math.max(1, ea - d);
        let hiBits = (fmt == "G")? 20 : 23;
        a = mk(fmt, (rng() < 0.5)? 1 : 0, ea, mkFrac(rng, hiBits, pick(rng, FRAC_PATTERNS)),
            mkFrac(rng, 32, pick(rng, FRAC_PATTERNS)));
        b = mk(fmt, (rng() < 0.5)? 1 : 0, eb, mkFrac(rng, hiBits, pick(rng, FRAC_PATTERNS)),
            mkFrac(rng, 32, pick(rng, FRAC_PATTERNS)));
        break;
    }

    case "overflow": {
        if (!op.arith) return null;
        ctx.add("overflow");
        let hiBits = (fmt == "G")? 20 : 23;
        let ea = rndInt(rng, f.maxexp - 2, f.maxexp);
        /* multiply two big ones, or divide a big one by a tiny one */
        let eb = op.div? rndInt(rng, 1, 3) : rndInt(rng, f.maxexp - 2, f.maxexp);
        a = mk(fmt, (rng() < 0.5)? 1 : 0, op.div? eb : ea,
            mkFrac(rng, hiBits, "ones"), mkFrac(rng, 32, "ones"));
        b = mk(fmt, (rng() < 0.5)? 1 : 0, op.div? ea : eb,
            mkFrac(rng, hiBits, "ones"), mkFrac(rng, 32, "ones"));
        break;
    }

    case "underflow": {
        if (!op.arith) return null;
        ctx.add("underflow");
        ctx.add("tinyexp");
        let hiBits = (fmt == "G")? 20 : 23;
        let ea = rndInt(rng, 1, 4);
        let eb = op.div? rndInt(rng, f.maxexp - 4, f.maxexp) : rndInt(rng, 1, 4);
        a = mk(fmt, (rng() < 0.5)? 1 : 0, ea, mkFrac(rng, hiBits, pick(rng, FRAC_PATTERNS)),
            mkFrac(rng, 32, pick(rng, FRAC_PATTERNS)));
        b = mk(fmt, (rng() < 0.5)? 1 : 0, eb, mkFrac(rng, hiBits, pick(rng, FRAC_PATTERNS)),
            mkFrac(rng, 32, pick(rng, FRAC_PATTERNS)));
        break;
    }

    case "divzero": {
        if (!op.div) return null;
        ctx.add("divzero");
        ctx.add("zero");
        a = mk(fmt, 0, 0, 0, 0);                        // opnd[0] is the DIVISOR
        b = genValue(rng, fmt, "plain", ctx);
        break;
    }

    case "sameval": {
        a = genValue(rng, fmt, pick(rng, ["plain", "unit", "tinyexp", "maxexp"]), ctx);
        b = (rng() < 0.5)? a.slice() : a.map((x, i) => (i == 0? (x ^ FPSIGN) | 0 : x));
        ctx.add("ediff0");
        break;
    }

    default:
        a = genValue(rng, fmt, cls, ctx);
        b = genValue(rng, fmt, (rng() < 0.4)? cls : "plain", ctx);
        break;
    }

    if (op.div && getExp(fmt, a) == 0 && !(a[0] & FPSIGN)) ctx.add("divzero");
    let ea = getExp(fmt, a), eb = getExp(fmt, b);
    if (ea && eb) {
        let d = Math.abs(ea - eb);
        if (d == 0) ctx.add("ediff0");
        else if (d < 32) ctx.add("ediff1_31");
        else if (d < 64) ctx.add("ediff32_63");
        else ctx.add("ediff64");
    }
    return a.concat(b);
}

/**
 * genCases(rng, nCases)
 *
 * @param {function(): number} rng
 * @param {number} nCases
 * @returns {Array.<Object>}
 */
function genCases(rng, nCases)
{
    let classes = [];
    for (let [name, w] of CASE_CLASSES) for (let i = 0; i < w; i++) classes.push(name);

    let cases = [];
    let nMem = 0;
    for (let i = 0; i < nCases; i++) {
        /*
         * Round-robin over the opcode table rather than uniform random selection, so the
         * per-opcode floor is met by construction and not by luck.  The class is random.
         */
        let op = OPS[i % OPS.length];
        let cls, srcs, ctx;
        for (let tries = 0; ; tries++) {
            ctx = new Set();
            cls = (tries < 6)? pick(rng, classes) : "plain";
            srcs = genSrcs(rng, op, cls, ctx);
            if (srcs) break;
        }

        /*
         * Destination.  A `spec` above GRN|nPC (0x5F) means memory; anything at or below it is
         * register mode, and the register number is what WRITE_* stores through.  R14/R15 are
         * generated deliberately for quadword destinations, where they are a reserved ADDRESSING
         * mode fault -- SIMH's RSVD_ADDR_FAULT inside WRITE_Q.
         */
        let c = {index: i, op, cls, srcs, cls_set: ctx};
        let wantResad = (op.dest == "Q") && (rng() < 0.02);
        if (wantResad) {
            c.spec = 0x50; c.rn = pick(rng, [14, 15]); c.va = 0;
            ctx.add("resad");
        } else if (op.dest && rng() < 0.42) {
            c.spec = 0x60;
            c.va = (DST_BASE + nMem * DST_STRIDE + (rng() < 0.25? pick(rng, [1, 2, 4, 6]) : 0)) | 0;
            c.rn = rndInt(rng, 0, 13);
            c.slot = nMem++;
            ctx.add("memDest");
        } else {
            c.spec = 0x50;
            c.rn = rndInt(rng, 0, 13);
            c.va = 0;
            if (op.dest) ctx.add("regDest");
        }
        c.d0 = rnd32(rng);
        c.d1 = rnd32(rng);
        c.psl = (rng() < 0.5? PSW_FU : 0) | (rng() < 0.5? PSW_IV : 0);
        c.cc = rndInt(rng, 0, 15);
        cases.push(c);
    }
    return {cases, nMem};
}

/* ------------------------------------------------------------------------------------------- *
 * Talking to SIMH
 * ------------------------------------------------------------------------------------------- */

/**
 * findSimh(argPath)
 *
 * @param {?string} argPath
 * @returns {string}
 */
function findSimh(argPath)
{
    /*
     * An explicit --simh that does not exist is an ERROR, not the head of a fallback list.
     * Silently grading against a different binary than the one you named is the kind of thing
     * that costs an afternoon.
     */
    if (argPath && !fs.existsSync(argPath)) {
        throw new Error("--simh " + argPath + " does not exist");
    }
    let candidates = [
        argPath,
        process.env["SIMH_FP_BIN"],
        process.env["SIMH_BIN"],
        path.join(os.tmpdir(), "pcjs-vax-simh-fp/open-simh/BIN/microvax3900"),
        path.join(os.tmpdir(), "pcjs-vax-simh/open-simh/BIN/microvax3900")
    ].filter((p) => !!p);
    for (let p of candidates) {
        if (fs.existsSync(p)) return p;
    }
    throw new Error("microvax3900 binary not found (tried: " + candidates.join(", ") + ").\n" +
        "This test grades against REAL SIMH and has no fixture fallback.  Build it with\n" +
        "    machines/dec/vax/tests/simh/build.sh $TMPDIR/pcjs-vax-simh-fp\n" +
        "then pass --simh PATH or set SIMH_FP_BIN.  The stock simulator is NOT sufficient:\n" +
        "patch 0004 adds SHOW CPU FPOP=, which this test requires.");
}

/**
 * findEhkaa()
 *
 * The diagnostic lives in the pcjs-vax work repo beside this one.  "Beside" is resolved the same
 * way build.sh resolves it, including the $PCJS_VAX_REPO override -- without which nothing here
 * works from a git worktree, whose parent directory is .worktrees rather than the project root.
 *
 * @returns {string}
 */
function findEhkaa()
{
    let roots = [
        process.env["PCJS_VAX_REPO"],
        path.resolve(REPO_ROOT, "../pcjs-vax"),
        path.resolve(REPO_ROOT, "../../pcjs-vax"),
        path.resolve(os.homedir(), "projects/pcjs-vax")
    ].filter((p) => !!p);
    for (let r of roots) {
        let p = path.join(r, "open-simh/VAX/tests/ehkaa.exe");
        if (fs.existsSync(p)) return p;
    }
    return path.join(roots[0], "open-simh/VAX/tests/ehkaa.exe");
}

/**
 * runSimh(bin, script, iniPath)
 *
 * @param {string} bin
 * @param {string} script
 * @param {string} iniPath
 * @returns {string} stdout
 */
function runSimh(bin, script, iniPath)
{
    fs.writeFileSync(iniPath, script);
    return execFileSync(bin, [iniPath], {encoding: "utf8", maxBuffer: 1 << 30,
        stdio: ["ignore", "pipe", "pipe"]});
}

/**
 * requireFpSupport(simhBin, scratch)
 *
 * Fails loudly and early if the simulator predates patch 0004, rather than letting every
 * comparison mysteriously report "no FPOP line".  The probe is ADDF3 1.0 + 1.0 = 2.0, whose
 * answer is checked, so a simulator that accepts the command but computes nonsense is caught
 * here rather than 60,000 lines later.
 *
 * @param {string} simhBin
 * @param {string} scratch
 */
function requireFpSupport(simhBin, scratch)
{
    let out = runSimh(simhBin, "set cpu 16m\nshow cpu fpop=41:0:0:50:0:0:0:0:2:4080:4080\nquit\n",
        path.join(scratch, "fpprobe.ini"));
    let m = /^FPOP 041 ok \w+ \w+ (\w+) /m.exec(out);
    if (!m) {
        throw new Error("this simulator does not implement SHOW CPU FPOP=; rebuild it with\n" +
            "    machines/dec/vax/tests/simh/build.sh $TMPDIR/pcjs-vax-simh-fp\n" +
            "which applies patch 0004-fp-differential-support.patch.  SIMH said:\n" + out);
    }
    if (parseInt(m[1], 16) != 0x4100) {
        throw new Error("SHOW CPU FPOP= is present but ADDF3 1.0+1.0 did not give 2.0 (got " +
            m[1] + "); the simulator or the patch is wrong, and nothing below would mean anything.");
    }
}

/**
 * fpopCommand(c)
 *
 * @param {Object} c
 * @returns {string}
 */
function fpopCommand(c)
{
    let f = [hex(c.op.opc), hex(c.psl), hex(c.cc), hex(c.spec), hex(c.rn), hex(c.va),
        hex(c.d0), hex(c.d1), c.srcs.length.toString(16).toUpperCase()];
    for (let v of c.srcs) f.push(hex(v));
    return "show cpu fpop=" + f.join(":");
}

const FPOP_OK_RE    = /^FPOP ([0-9A-F]{3}) ok ([0-9A-F]+) ([0-9A-F]{8}) ([0-9A-F]{8}) ([0-9A-F]{8})$/;
const FPOP_ABORT_RE = /^FPOP ([0-9A-F]{3}) abort (-?\d+) ([0-9A-F]{8}) ([0-9A-F]{8})$/;

/**
 * parseFpop(line)
 *
 * @param {string} line
 * @returns {?Object}
 */
function parseFpop(line)
{
    let m = FPOP_OK_RE.exec(line);
    if (m) {
        return {opc: parseInt(m[1], 16), ok: true, cc: parseInt(m[2], 16),
            trpirq: parseInt(m[3], 16) | 0, r0: parseInt(m[4], 16) | 0, r1: parseInt(m[5], 16) | 0};
    }
    m = FPOP_ABORT_RE.exec(line);
    if (m) {
        return {opc: parseInt(m[1], 16), ok: false, code: parseInt(m[2], 10),
            p1: parseInt(m[3], 16) | 0, p2: parseInt(m[4], 16) | 0};
    }
    return null;
}

/* ------------------------------------------------------------------------------------------- *
 * The JS side
 * ------------------------------------------------------------------------------------------- */

/**
 * makeMachine(mutation)
 *
 * A machine with memory management OFF, so a virtual address is a physical address and the
 * EXERCISER phase's memory destinations land where DEPOSIT put SIMH's.
 *
 * @param {string} mutation
 * @returns {Object}
 */
function makeMachine(mutation)
{
    let bus = new BusVAX({'busWidth': VAX.PAWIDTH, 'id': "bus"}, null, null);
    bus.addMemory(0, MEMSIZE, MemoryVAX.TYPE.RAM);
    let mmu = new MMUVAX(bus);
    mmu.setMAPEN(0);

    let cpu = {
        regs: new Int32Array(16),
        psl: 0,
        cc: 0,
        trpirq: 0,
        acc: MMUVAX.accRead(0),                         // kernel; ACC_MASK(KERN)
        decoder: {opnd: new Int32Array(16), spec: 0, rn: 0, va: 0},
        mmu
    };
    let fpu = new VAXFloat(cpu);
    if (mutation) applyMutation(fpu, mutation);
    return {bus, mmu, cpu, fpu};
}

/**
 * runCase(m, c)
 *
 * Run one case on the JS side and return the same shape parseFpop() returns, so the comparison
 * is field by field rather than a stringified blob.
 *
 * @param {Object} m
 * @param {Object} c
 * @returns {Object}
 */
function runCase(m, c)
{
    let {cpu, fpu} = m;
    let d = cpu.decoder;
    for (let i = 0; i < d.opnd.length; i++) d.opnd[i] = 0;
    for (let i = 0; i < c.srcs.length; i++) d.opnd[i] = c.srcs[i] | 0;
    d.spec = c.spec;
    d.rn = c.rn;
    d.va = c.va | 0;
    cpu.psl = c.psl;
    cpu.cc = c.cc;
    cpu.trpirq = 0;
    cpu.regs[c.rn] = c.d0 | 0;
    cpu.regs[(c.rn + 1) & 0xF] = c.d1 | 0;
    try {
        if (!fpu.execute(c.op.opc)) {
            return {err: "fpa.js did not handle opcode " + hex(c.op.opc)};
        }
    } catch (e) {
        if (e instanceof VAXFault) {
            return {ok: false, code: e.code, p1: e.p1 | 0, p2: e.p2 | 0};
        }
        throw e;
    }
    return {ok: true, cc: cpu.cc, trpirq: cpu.trpirq | 0,
        r0: cpu.regs[c.rn] | 0, r1: cpu.regs[(c.rn + 1) & 0xF] | 0};
}

/**
 * describeCase(c)
 *
 * @param {Object} c
 * @returns {string}
 */
function describeCase(c)
{
    return c.op.name + " [" + c.cls + "] opnd=" + c.srcs.map((v) => hex(v, 8)).join(",") +
        " spec=" + hex(c.spec, 2) + " rn=" + c.rn + " va=" + hex(c.va, 8) +
        " psl=" + hex(c.psl, 2) + " cc=" + hex(c.cc);
}

/**
 * compare(sim, js, where, fail)
 *
 * @param {Object} sim
 * @param {Object} js
 * @param {string} where
 * @param {function(string): void} fail
 * @returns {boolean} true if identical
 */
function compare(sim, js, where, fail)
{
    if (js.err) { fail(where + ": " + js.err); return false; }
    if (sim.ok != js.ok) {
        fail(where + ": SIMH " + (sim.ok? "completed" : "aborted " + sim.code) +
            ", we " + (js.ok? "completed" : "faulted " + js.code));
        return false;
    }
    if (!sim.ok) {
        if (sim.code != js.code) {
            fail(where + ": abort code SIMH=" + sim.code + " ours=" + js.code);
            return false;
        }
        /*
         * p1/p2 are only meaningful for the arithmetic abort.  SIMH's reserved-operand and
         * reserved-address aborts leave whatever the last fault put there, which is why they
         * are not compared -- comparing them would be comparing stale globals.
         */
        if (sim.code == ABORT_ARITH && sim.p1 != js.p1) {
            fail(where + ": arithmetic trap parameter SIMH=" + hex(sim.p1) + " ours=" + hex(js.p1));
            return false;
        }
        return true;
    }
    if (sim.cc != js.cc) {
        fail(where + ": cc SIMH=" + hex(sim.cc) + " ours=" + hex(js.cc));
        return false;
    }
    if (sim.trpirq != js.trpirq) {
        fail(where + ": trpirq SIMH=" + hex(sim.trpirq, 8) + " ours=" + hex(js.trpirq, 8));
        return false;
    }
    if (sim.r0 != js.r0 || sim.r1 != js.r1) {
        fail(where + ": result SIMH=" + hex(sim.r0, 8) + "," + hex(sim.r1, 8) +
            " ours=" + hex(js.r0, 8) + "," + hex(js.r1, 8));
        return false;
    }
    return true;
}

/* ------------------------------------------------------------------------------------------- *
 * Phase 1: the randomized exerciser
 * ------------------------------------------------------------------------------------------- */

/**
 * newStats()
 *
 * @returns {Object}
 */
function newStats()
{
    let s = {
        nCases: 0, nCompared: 0, nOK: 0, nFaulted: 0,
        nNonTrivial: 0, nResultChecks: 0,
        byOpcode: new Map(),
        cls: new Map()
    };
    for (let k of ["zero", "resop", "negzero", "tinyexp", "maxexp", "roundTie", "roundNear",
        "cancellation", "ediff0", "ediff1_31", "ediff32_63", "ediff64", "overflow", "underflow",
        "underflowFault", "divzero", "intovf", "intovfTrap", "intbound", "resad", "memDest",
        "regDest"]) {
        s.cls.set(k, 0);
    }
    for (let op of OPS) s.byOpcode.set(op.opc, 0);
    return s;
}

/**
 * bump(stats, key)
 *
 * @param {Object} stats
 * @param {string} key
 */
function bump(stats, key)
{
    stats.cls.set(key, (stats.cls.get(key) || 0) + 1);
}

/**
 * buildExerciserIni(cases, nMem)
 *
 * @param {Array.<Object>} cases
 * @param {number} nMem
 * @returns {Object}
 */
function buildExerciserIni(cases, nMem)
{
    let L = ["set cpu " + (MEMSIZE >> 20) + "m"];
    let dstEnd = DST_BASE + Math.max(nMem, 1) * DST_STRIDE - 4;
    /*
     * One ranged deposit rather than four per case: the prior contents only matter for the
     * byte and word destinations' read-modify-write, and a single known pattern makes the
     * final sweep trivially attributable while keeping the command stream small.
     */
    L.push("dep -l " + hex(DST_BASE) + "-" + hex(dstEnd) + " " + hex(DST_FILL, 8));
    let nPrologue = 0;
    for (let c of cases) L.push(fpopCommand(c));
    L.push("e -l " + hex(DST_BASE) + "-" + hex(dstEnd));
    L.push("quit", "");
    return {text: L.join("\n"), nPrologue, dstEnd};
}

/**
 * runExerciser(simhBin, nCases, seed, mutation, scratch, fQuiet)
 *
 * @param {string} simhBin
 * @param {number} nCases
 * @param {number} seed
 * @param {string} mutation
 * @param {string} scratch
 * @param {boolean} fQuiet
 * @returns {Object} {failures, stats}
 */
function runExerciser(simhBin, nCases, seed, mutation, scratch, fQuiet)
{
    let rng = mulberry32(seed);
    let {cases, nMem} = genCases(rng, nCases);
    let stats = newStats();
    let failures = [];
    let fail = (s) => { if (failures.length < 25) failures.push(s); };

    let {text, nPrologue, dstEnd} = buildExerciserIni(cases, nMem);
    let out = runSimh(simhBin, text, path.join(scratch, "fpexer.ini"));

    let aFpop = [], aExam = [], aErrors = [];
    for (let line of out.split("\n")) {
        let t = line.replace(/\r$/, "");
        if (t.startsWith("FPOP ")) aFpop.push(t);
        else if (/^[0-9A-F]{1,8}:\t[0-9A-F]{8}$/.test(t)) aExam.push(t);
        else if (/%SIM-ERROR|Invalid argument|Non-existent device/.test(t)) aErrors.push(t.trim());
    }
    for (let e of aErrors) fail("SIMH reported an error: " + e);

    /*
     * NOTHING MAY BE SILENTLY DROPPED.  Every case must have produced exactly one FPOP line.
     * A shifted stream would keep "passing" for a while, so say WHICH case lost its line.
     */
    if (aFpop.length != nPrologue + cases.length) {
        fail("SIMH produced " + aFpop.length + " FPOP lines for " + cases.length +
            " cases; " + (cases.length - aFpop.length) + " were dropped");
    }

    let m = makeMachine(mutation);
    for (let pa = DST_BASE; pa <= dstEnd; pa += 4) m.bus.setLong(pa, DST_FILL);

    for (let i = 0; i < cases.length; i++) {
        let c = cases[i];
        let where = "case " + i + " " + describeCase(c);
        let line = aFpop[nPrologue + i];
        if (!line) { fail(where + ": SIMH produced no FPOP line"); continue; }
        let sim = parseFpop(line);
        if (!sim) { fail(where + ": unparseable SIMH line '" + line + "'"); continue; }
        if (sim.opc != c.op.opc) {
            fail(where + ": SIMH line is for opcode " + hex(sim.opc) + ", stream is out of step");
            continue;
        }
        let js = runCase(m, c);
        stats.nCases++;
        stats.byOpcode.set(c.op.opc, stats.byOpcode.get(c.op.opc) + 1);
        for (let k of c.cls_set) bump(stats, k);

        if (compare(sim, js, where, fail)) stats.nCompared++;

        if (sim.ok) {
            stats.nOK++;
            if (sim.trpirq) {
                bump(stats, "intovfTrap");
            }
            /*
             * "Non-trivial" here means the instruction actually computed something: the stored
             * result is neither zero nor a bit-for-bit copy of the first source operand.  A run
             * whose comparisons are mostly trivial has not tested the arithmetic, only the
             * plumbing -- which is the exact failure mode pcjsvax-cd6 shipped.
             */
            if (c.op.dest) {
                stats.nResultChecks++;
                let r0 = sim.r0;
                if (r0 != 0 && r0 != (c.srcs[0] | 0)) stats.nNonTrivial++;
            }
        } else {
            stats.nFaulted++;
            if (sim.code == ABORT_ARITH) {
                if (sim.p1 == FLT_OVRFLO) bump(stats, "overflow");
                else if (sim.p1 == FLT_UNDFLO) bump(stats, "underflowFault");
                else if (sim.p1 == FLT_DIVZRO) bump(stats, "divzero");
            }
        }
        if (sim.ok && (sim.cc & 0x02) && !c.op.arith && /^CVT[FDG][BWL]$|^CVTR/.test(c.op.name)) {
            bump(stats, "intovf");
        }
    }

    /* ---- the read-back sweep: every memory destination, compared to our memory ---- */
    let swept = new Map();
    for (let line of aExam) {
        let ix = line.indexOf(":");
        swept.set(parseInt(line.slice(0, ix), 16) >>> 0, parseInt(line.slice(ix + 2), 16) | 0);
    }
    let nSweep = 0, nSweepChanged = 0;
    for (let pa = DST_BASE; pa <= dstEnd; pa += 4) {
        if (!swept.has(pa >>> 0)) { fail("read-back sweep: SIMH did not report " + hex(pa, 8)); break; }
        let want = swept.get(pa >>> 0);
        let got = m.bus.getLong(pa) | 0;
        nSweep++;
        if (want != DST_FILL) nSweepChanged++;
        if (want != got) {
            fail("read-back sweep at " + hex(pa, 8) + " (case " + ((pa - DST_BASE) / DST_STRIDE | 0) +
                "): SIMH=" + hex(want, 8) + " ours=" + hex(got, 8));
        }
    }
    stats.nSweep = nSweep;
    stats.nSweepChanged = nSweepChanged;
    stats.nMem = nMem;
    if (!fQuiet && nMem > 0 && nSweepChanged == 0) {
        fail("read-back sweep: not one memory destination was written -- the sweep proves nothing");
    }
    return {failures, stats};
}

/* ------------------------------------------------------------------------------------------- *
 * Phase 2: EHKAA, the real workload
 *
 * The DEC hardware core diagnostic executes roughly 700 F/D/G instructions out of its 335,444
 * (docs/reference/ehkaa-profile.md §2).  They are worth grading for one reason the exerciser
 * cannot supply: they are the operand values and the opcode mix a REAL PROGRAM produces, chosen
 * by DEC's own engineers to exercise the hardware, and pcjsvax-061 is the standing evidence that
 * a real workload finds things a generator does not.
 *
 * Two gradings per instruction:
 *
 *   (a) IN SITU.  The history record prints the instruction's own result (`-> hi lo`), produced
 *       by the diagnostic actually executing.  We compare ours to it.  This is skipped when the
 *       instruction faulted, because SIMH fills the result field from `r`/`rh` at the top of the
 *       NEXT loop iteration and an aborted instruction never assigned them -- the printed value
 *       is the previous instruction's and means nothing.
 *
 *   (b) FPOP REPLAY.  The same opcode and operand queue driven back through SHOW CPU FPOP=,
 *       which additionally grades the condition codes, the trap request and the fault code.
 * ------------------------------------------------------------------------------------------- */

const INSTR_LINE_RE = /^([0-9A-Fa-f]{8}) ([0-9A-Fa-f]{8})\| (.*)$/;

/**
 * parseFpRecords(pathTrace)
 *
 * Streams the EHKAA capture and returns one entry per F/D/G instruction.  Streaming rather than
 * slurping matters: a full capture is a few hundred megabytes.
 *
 * The opcode comes from the `IBYT` line (patch 0002) rather than from the disassembled mnemonic,
 * so a two-byte FD-prefixed G_floating opcode is exact and not a string match.
 *
 * @param {string} pathTrace
 * @returns {Object} {recs, nTotal}
 */
function parseFpRecords(pathTrace)
{
    const fd = fs.openSync(pathTrace, "r");
    const CHUNK = 1 << 22;
    let buf = Buffer.allocUnsafe(CHUNK);
    let carry = "";
    let rec = null, nTotal = 0, lineno = 0;
    let recs = [];
    let pending = null;                 // the previous FP record, awaiting the next PSL for its cc

    const fields = (line) => {
        let sp = line.indexOf(" ");
        return sp < 0 ? [] : line.slice(sp + 1).split(" ");
    };

    const finish = (r) => {
        if (pending) {
            pending.ccAfter = r? (r.psl & 0xF) : -1;
            pending.pcAfter = r? r.pc : 0;
            pending = null;
        }
    };

    const handleLine = (line) => {
        lineno++;
        let mm = INSTR_LINE_RE.exec(line);
        if (mm) {
            if (rec) throw new Error(pathTrace + ":" + lineno +
                ": new record before the previous one completed -- unpatched SIMH or truncated capture?");
            rec = {pc: parseInt(mm[1], 16) | 0, psl: parseInt(mm[2], 16) | 0, detail: mm[3]};
            finish(rec);
            return;
        }
        if (!rec) return;
        if (line.startsWith("IBYT ")) {
            let f = fields(line);
            let b0 = parseInt(f[1], 16);
            rec.opc = (b0 == 0xFD)? (parseInt(f[2], 16) | 0x100) : b0;
            return;
        }
        if (line.startsWith("OPND ")) {
            let f = fields(line);
            rec.nopnd = +f[0];
            rec.opnd = f.slice(1).map((t) => parseInt(t, 16) | 0);
            return;
        }
        if (line.startsWith("BRDP ")) {
            nTotal++;
            if (rec.opnd === undefined || rec.opc === undefined) {
                throw new Error(pathTrace + ":" + lineno +
                    ": record at PC=" + hex(rec.pc, 8) + " is missing IBYT/OPND -- was the capture" +
                    ' made with "set -d cpu history=..."?');
            }
            if (OPS_BY_OPC.has(rec.opc)) {
                let m = / -> ((?:[0-9A-F]{8} ?)+)/.exec(rec.detail);
                rec.res = m? m[1].trim().split(/\s+/).map((t) => parseInt(t, 16) | 0) : null;
                recs.push(rec);
                pending = rec;
            }
            rec = null;
            return;
        }
        if (line.startsWith(" ")) { rec.detail += " " + line.trim(); return; }
    };

    for (;;) {
        let n = fs.readSync(fd, buf, 0, CHUNK, null);
        if (n <= 0) break;
        let s = carry + buf.toString("latin1", 0, n);
        let start = 0;
        for (;;) {
            let nl = s.indexOf("\n", start);
            if (nl < 0) break;
            let line = s.slice(start, nl);
            if (line.endsWith("\r")) line = line.slice(0, -1);
            handleLine(line);
            start = nl + 1;
        }
        carry = s.slice(start);
    }
    if (carry.length) handleLine(carry.replace(/\r$/, ""));
    finish(null);
    fs.closeSync(fd);
    return {recs, nTotal};
}

/**
 * runEhkaa(simhBin, opts, mutation, scratch)
 *
 * @param {string} simhBin
 * @param {Object} opts
 * @param {string} mutation
 * @param {string} scratch
 * @returns {Object}
 */
function runEhkaa(simhBin, opts, mutation, scratch)
{
    let tracePath = opts.trace;
    if (!tracePath) {
        let ehkaa = opts.ehkaaExe;
        if (!fs.existsSync(ehkaa)) {
            throw new Error("EHKAA diagnostic not found at " + ehkaa +
                "; pass --ehkaa PATH or --skip-ehkaa");
        }
        tracePath = path.join(scratch, "ehkaa.trace");
        let script = [
            "set -d cpu history=100000:" + tracePath,
            "load " + ehkaa,
            "go -q 200",
            "examine PC",
            "exit", ""
        ].join("\n");
        let out = runSimh(simhBin, script, path.join(scratch, "ehkaa.ini"));
        if (!/PC:\s*80018AD1/.test(out)) {
            throw new Error("EHKAA did not halt at its documented PASS PC (0x80018AD1); SIMH said:\n" + out);
        }
    }

    let {recs, nTotal} = parseFpRecords(tracePath);
    let failures = [];
    let fail = (s) => { if (failures.length < 25) failures.push(s); };
    let stats = {nTotal, nFp: recs.length, nReplayed: 0, nInSitu: 0, nFaulted: 0,
        byOpcode: new Map()};

    /*
     * Replay every one of them through FPOP, in one simulator run.  The destination is always a
     * register here: EHKAA's own destinations are wherever the diagnostic put them, and what is
     * being graded in this phase is the ARITHMETIC on real operands, not the store -- which the
     * exerciser and the QUADSTORE phase grade directly.
     */
    let cases = recs.map((r, i) => {
        let op = OPS_BY_OPC.get(r.opc);
        let nsrc = op.srcs.reduce((n, f) => n + ((f == "D" || f == "G")? 2 : 1), 0);
        return {
            index: i, op, cls: "ehkaa",
            srcs: r.opnd.slice(0, nsrc).map((v) => v | 0),
            spec: 0x50, rn: 0, va: 0, d0: 0, d1: 0,
            psl: r.psl & (PSW_FU | PSW_IV), cc: r.psl & 0xF, cls_set: new Set()
        };
    });
    let L = ["set cpu " + (MEMSIZE >> 20) + "m"];
    for (let c of cases) L.push(fpopCommand(c));
    L.push("quit", "");
    let out = runSimh(simhBin, L.join("\n"), path.join(scratch, "fpehkaa.ini"));
    let aFpop = out.split("\n").map((s) => s.replace(/\r$/, "")).filter((s) => s.startsWith("FPOP "));
    if (aFpop.length != cases.length) {
        fail("EHKAA replay: SIMH produced " + aFpop.length + " FPOP lines for " +
            cases.length + " F/D/G instructions; " + (cases.length - aFpop.length) + " were dropped");
    }

    let m = makeMachine(mutation);
    for (let i = 0; i < cases.length; i++) {
        let c = cases[i], r = recs[i];
        let where = "EHKAA PC=" + hex(r.pc, 8) + " " + describeCase(c);
        let line = aFpop[i];
        if (!line) { fail(where + ": SIMH produced no FPOP line"); continue; }
        let sim = parseFpop(line);
        if (!sim || sim.opc != c.op.opc) {
            fail(where + ": unparseable or out-of-step SIMH line '" + line + "'");
            continue;
        }
        let js = runCase(m, c);
        stats.nReplayed++;
        stats.byOpcode.set(c.op.name, (stats.byOpcode.get(c.op.name) || 0) + 1);
        compare(sim, js, where, fail);
        if (!sim.ok) { stats.nFaulted++; continue; }

        /*
         * (a) in situ.  Only when the instruction completed AND the record printed a result AND
         * the opcode stores one -- TSTx and CMPx have no result field.
         */
        if (js.ok && r.res && c.op.dest) {
            let want0 = r.res[0] | 0;
            let got0 = js.r0 | 0;
            let ok = (want0 == got0);
            if (ok && c.op.dest == "Q" && r.res.length > 1) ok = ((r.res[1] | 0) == (js.r1 | 0));
            if (!ok) {
                fail(where + ": in-situ result SIMH printed " +
                    r.res.map((v) => hex(v, 8)).join(",") + " ours=" + hex(js.r0, 8) +
                    (c.op.dest == "Q"? "," + hex(js.r1, 8) : ""));
            }
            stats.nInSitu++;
        }
    }
    return {failures, stats};
}

/* ------------------------------------------------------------------------------------------- *
 * Phase 3: WRITE_Q's cross-page probe, with memory management ON
 *
 * SIMH's WRITE_Q (vax_cpu.c:221) is three statements whose INDENTATION LIES: the `if` guards only
 * the low-longword Write, and the high-longword Write is unconditional.
 *
 *      if ((Test (va + 7, WA, &mstat) >= 0) || (Test (va, WA, &mstat) < 0))
 *          Write (va, arl, L_LONG, WA);
 *      Write (va + 4, arh, L_LONG, WA);
 *
 * That produces three distinct behaviours, and a "cleaner" rewrite gets the third one wrong:
 *
 *      both pages OK      write low, write high.
 *      second page bad    the low write is SKIPPED and the high write faults -- so a quadword
 *                         straddling into an inaccessible page stores NOTHING and the
 *                         instruction stays restartable.
 *      first page bad     the low write runs and faults, so when BOTH pages are bad the fault
 *                         reported is the FIRST page's, which is what the architecture requires.
 *
 * None of that is reachable with MAPEN off, so this phase builds a small system page table with
 * pages that are readable-but-not-writable, no-access and invalid, and stores quadwords across
 * every boundary between them.  Both sides then read the whole data area back.
 * ------------------------------------------------------------------------------------------- */

const Q_SBR         = 0x00400000;       // system page table, physical
const Q_PAGES       = 128;              // S0 pages mapped
const Q_SLR         = Q_PAGES;          // longwords in the SPT
const Q_DATA_PA     = 0x00100000;       // first data frame
const Q_S0          = 0x80000000 | 0;

const IPR = {SBR: 12, SLR: 13, MAPEN: 56, TBIA: 57};

/* PTE protection codes, from the CVTACC table in mmu.js: 0 = no access, 2 = kernel read/write,
 * 3 = kernel read only.  Everything here runs in kernel mode, so those three are exactly the
 * "writable", "readable but not writable" and "not there at all" cases. */
const Q_PROT_RW = 2, Q_PROT_RO = 3, Q_PROT_NA = 0;

/**
 * buildQuadLayout(rng)
 *
 * @param {function(): number} rng
 * @returns {Object}
 */
function buildQuadLayout(rng)
{
    let mem = new Map();
    let pages = [];
    for (let i = 0; i < Q_PAGES; i++) {
        /*
         * A deliberately dense mixture: roughly half the pages are writable, and the rest are
         * split between read-only, no-access and invalid, so that consecutive pairs cover all
         * sixteen combinations of (first page state, second page state) many times over.
         */
        let kind = pick(rng, ["rw", "rw", "rw", "rw", "ro", "na", "inv", "rw", "ro", "na"]);
        pages.push(kind);
        let pfn = (Q_DATA_PA / 512) + i;
        let prot = (kind == "rw")? Q_PROT_RW : (kind == "ro")? Q_PROT_RO : Q_PROT_NA;
        let pte = (kind == "inv")? 0 : ((0x80000000 | (prot << 27) | pfn) | 0);
        mem.set(Q_SBR + i * 4, pte);
        for (let off = 0; off < 512; off += 4) {
            mem.set(Q_DATA_PA + i * 512 + off, (0x11110000 + i * 0x100 + off) | 0);
        }
    }
    return {mem, pages};
}

/**
 * runQuadStore(simhBin, seed, mutation, scratch)
 *
 * @param {string} simhBin
 * @param {number} seed
 * @param {string} mutation
 * @param {string} scratch
 * @returns {Object}
 */
function runQuadStore(simhBin, seed, mutation, scratch)
{
    let rng = mulberry32(seed ^ 0x5EED5EED);
    let layout = buildQuadLayout(rng);
    let failures = [];
    let fail = (s) => { if (failures.length < 25) failures.push(s); };
    let stats = {nCases: 0, nFaulted: 0, nStraddle: 0, nOK: 0, nUnaligned: 0};

    /* the quadword-destination opcodes, and offsets that put the store on, over and past the
     * page boundary -- including unaligned ones, which additionally split each longword */
    const QOPS = [OPC.MOVD, OPC.MOVG, OPC.ADDD3, OPC.ADDG3, OPC.MULD3, OPC.CVTLD, OPC.CVTLG];
    const OFFS = [0x000, 0x1F0, 0x1F4, 0x1F6, 0x1F8, 0x1FA, 0x1FC, 0x1FE, 0x1FF, 0x200, 0x202];

    let cases = [];
    for (let i = 0; i < Q_PAGES - 1; i++) {
        for (let off of OFFS) {
            let opc = QOPS[(i + off) % QOPS.length];
            let op = OPS_BY_OPC.get(opc);
            let srcs = [];
            let nsrc = op.srcs.reduce((n, f) => n + ((f == "D" || f == "G")? 2 : 1), 0);
            for (let k = 0; k < nsrc; k++) {
                srcs.push(op.srcs[0] == "l"? (i * 977 + off) : mk(op.srcs[0], 0,
                    (op.srcs[0] == "G")? 0x400 + (k + 1) : 0x80 + (k + 1),
                    0x123456 + i, 0x89ABCDEF)[k & 1]);
            }
            if (op.srcs[0] == "l") srcs = [(i * 977 + off) | 0];
            else {
                srcs = [];
                for (let k = 0; k < op.srcs.length; k++) {
                    let v = mk(op.srcs[0], 0,
                        (op.srcs[0] == "G")? 0x400 + k + 1 : 0x80 + k + 1,
                        (0x123456 + i * 7 + k) & 0x7FFFFF, (0x89ABCDEF + off) | 0);
                    srcs = srcs.concat(v);
                }
            }
            cases.push({
                index: cases.length, op, cls: "quad", srcs,
                spec: 0x60, rn: 0, va: (Q_S0 + i * 512 + off) | 0,
                d0: 0, d1: 0, psl: 0, cc: 0, cls_set: new Set(),
                page: i, off
            });
        }
    }

    /* ---- SIMH ---- */
    let L = ["set cpu " + (MEMSIZE >> 20) + "m", "dep psl 0"];
    for (let [pa, val] of layout.mem) L.push("dep -l " + hex(pa) + " " + hex(val, 8));
    L.push("show cpu mmuop=4:" + hex(Q_SBR) + ":1:0:" + hex(IPR.SBR));
    L.push("show cpu mmuop=4:" + hex(Q_SLR) + ":1:0:" + hex(IPR.SLR));
    L.push("show cpu mmuop=4:1:1:0:" + hex(IPR.MAPEN));
    let nPrologue = 3;
    for (let c of cases) L.push(fpopCommand(c));
    L.push("e -l " + hex(Q_DATA_PA) + "-" + hex(Q_DATA_PA + Q_PAGES * 512 - 4));
    L.push("quit", "");
    let out = runSimh(simhBin, L.join("\n"), path.join(scratch, "fpquad.ini"));

    let aFpop = [], aExam = [], aMmuop = 0;
    for (let line of out.split("\n")) {
        let t = line.replace(/\r$/, "");
        if (t.startsWith("FPOP ")) aFpop.push(t);
        else if (t.startsWith("MMUOP ")) aMmuop++;
        else if (/^[0-9A-F]{1,8}:\t[0-9A-F]{8}$/.test(t)) aExam.push(t);
        else if (/%SIM-ERROR|Invalid argument/.test(t)) fail("SIMH reported an error: " + t.trim());
    }
    if (aMmuop != nPrologue) fail("QUADSTORE: prologue produced " + aMmuop + " MMUOP lines, expected " + nPrologue);
    if (aFpop.length != cases.length) {
        fail("QUADSTORE: SIMH produced " + aFpop.length + " FPOP lines for " + cases.length +
            " cases; " + (cases.length - aFpop.length) + " were dropped");
    }

    /* ---- the JS side, with the same page tables ---- */
    let bus = new BusVAX({'busWidth': VAX.PAWIDTH, 'id': "bus"}, null, null);
    bus.addMemory(0, MEMSIZE, MemoryVAX.TYPE.RAM);
    for (let [pa, val] of layout.mem) bus.setLong(pa, val);
    let mmu = new MMUVAX(bus);
    mmu.setSBR(Q_SBR);
    mmu.setSLR(Q_SLR);
    mmu.setMAPEN(1);
    let cpu = {
        regs: new Int32Array(16), psl: 0, cc: 0, trpirq: 0,
        acc: MMUVAX.accRead(0),
        decoder: {opnd: new Int32Array(16), spec: 0, rn: 0, va: 0},
        mmu
    };
    let fpu = new VAXFloat(cpu);
    if (mutation) applyMutation(fpu, mutation);
    let m = {bus, mmu, cpu, fpu};

    for (let i = 0; i < cases.length; i++) {
        let c = cases[i];
        let where = "quad case " + i + " page " + c.page + "(" + layout.pages[c.page] + ")/" +
            (c.page + 1) + "(" + layout.pages[c.page + 1] + ") off=" + hex(c.off, 3) + " " +
            describeCase(c);
        let line = aFpop[i];
        if (!line) { fail(where + ": SIMH produced no FPOP line"); continue; }
        let sim = parseFpop(line);
        if (!sim) { fail(where + ": unparseable SIMH line '" + line + "'"); continue; }
        let js = runCase(m, c);
        stats.nCases++;
        if (c.off > 0x1F8) stats.nStraddle++;
        if (c.va & 3) stats.nUnaligned++;
        if (sim.ok) stats.nOK++; else stats.nFaulted++;
        if (!compare(sim, js, where, fail)) continue;
        if (!sim.ok && sim.code != ABORT_ARITH) {
            /* ACV/TNV carry p1 (the fault parameter) and p2 (the address); those we DO compare */
            if (sim.p1 != (js.p1 | 0) || sim.p2 != (js.p2 | 0)) {
                fail(where + ": fault parameters SIMH=" + hex(sim.p1, 8) + "," + hex(sim.p2, 8) +
                    " ours=" + hex(js.p1, 8) + "," + hex(js.p2, 8));
            }
        }
    }

    /* ---- read the whole data area back on both sides ---- */
    let swept = new Map();
    for (let line of aExam) {
        let ix = line.indexOf(":");
        swept.set(parseInt(line.slice(0, ix), 16) >>> 0, parseInt(line.slice(ix + 2), 16) | 0);
    }
    let nDiff = 0;
    for (let pa = Q_DATA_PA; pa < Q_DATA_PA + Q_PAGES * 512; pa += 4) {
        if (!swept.has(pa >>> 0)) { fail("QUADSTORE sweep: SIMH did not report " + hex(pa, 8)); break; }
        let want = swept.get(pa >>> 0), got = m.bus.getLong(pa) | 0;
        if (want != got) {
            fail("QUADSTORE sweep at " + hex(pa, 8) + ": SIMH=" + hex(want, 8) + " ours=" + hex(got, 8));
        }
        if (want != ((0x11110000 + ((pa - Q_DATA_PA) >> 9) * 0x100 + ((pa - Q_DATA_PA) & 0x1FF)) | 0)) nDiff++;
    }
    stats.nWritten = nDiff;
    return {failures, stats};
}

/* ------------------------------------------------------------------------------------------- *
 * The self-check: deliberate defects injected into the SHIPPED code path
 * ------------------------------------------------------------------------------------------- */

const MUTATIONS = [
    "fRoundAsD",        // F rounds at D's bit position -- THE rounding defect
    "gRoundHalf",       // G's round constant is half an ulp too small
    "normOnePass",      // norm() normalizes once instead of looping, so a deep cancellation is
                        // left unnormalized -- the cancellation/denormal defect
    "guardOneLess",     // one guard bit short on unpack, which moves every rounding decision
    "maxvNarrow",       // the float-to-integer overflow limit is one too small
    "resopSilent",      // a reserved operand is treated as zero -- the "negative zero" defect
    "ovflSilent",       // floating overflow returns a value instead of faulting
    "unflSilent",       // floating underflow ignores PSL<FU> and returns zero
    "mulNoCross",       // D/G multiply drops the 64-bit cross products
    "divPrecF",         // F divide develops 25 quotient bits instead of 26
    "addNoCarryNorm",   // floating add skips the renormalize when the fraction carries out
    "writeQNoProbe"     // WRITE_Q stores the low longword without probing the second page
];

/**
 * applyMutation(fpu, name)
 *
 * Some of these swap a table the shipped code reads, some wrap a shipped method, and two replace
 * a method with a minimally edited copy (marked CHANGED).  All of them are defects in the path
 * the differential actually exercises -- none is a test-only stub.
 *
 * The static tables are class properties, so a mutation of one is global; restoreMutations()
 * puts them back, and the self-check runs one mutation per process pass in any case.
 *
 * @param {VAXFloat} fpu
 * @param {string} name
 */
function applyMutation(fpu, name)
{
    switch (name) {

    case "fRoundAsD":
        VAXFloat.F_ROUND = {hi: 0x00000000, lo: 0x00000080};     /* CHANGED: D's constant */
        return;

    case "gRoundHalf":
        VAXFloat.G_ROUND = {hi: 0x00000000, lo: 0x00000200};     /* CHANGED: was 0x400 */
        return;

    case "normOnePass":
        /*
         * `while` becomes `if`: one normalizing step instead of as many as it takes.  A fraction
         * that lost one bit to cancellation still normalizes; one that lost twenty does not, so
         * this is caught only by the cancellation class and by nothing else.
         *
         * TWO MUTATIONS WERE TRIED HERE AND REJECTED, because both are worth knowing.
         *
         * Capping NORMTAB's last entry at 16 instead of 32 is provably UNOBSERVABLE: norm() is a
         * loop, so two shifts of 16 leave the fraction and the exponent exactly where one shift
         * of 32 does.  Every under-shift self-corrects on the next iteration.
         *
         * The opposite -- any OVER-shift, whether from a wrong NORMTAB entry or from a
         * NORMMASK[0] of 0x80000000 -- shifts the leading 1 off the top, and once the fraction
         * reaches zero the loop never terminates.  A mutation that HANGS is not a mutation; it
         * tests the harness's patience, not the oracle.
         */
        fpu.norm = function(r) {
            const normmask = VAXFloat.NORMMASK, normtab = VAXFloat.NORMTAB;
            if ((r.hi == 0) && (r.lo == 0)) { r.sign = r.exp = 0; return; }
            if ((r.hi & 0x80000000) == 0) {                      /* CHANGED: `if`, was `while` */
                let i;
                for (i = 0; i < 5; i++) { if (r.hi & normmask[i]) break; }
                dpLshT(r, normtab[i]);
                r.exp = r.exp - normtab[i];
            }
        };
        return;

    case "maxvNarrow":
        /* CHANGED: every float-to-integer limit is one too small */
        VAXFloat.MAXV = [0x7E, 0x7FFE, 0x7FFFFFFE, 0x7FFFFFFE];
        return;

    case "guardOneLess": {
        let uf = fpu.unpackf.bind(fpu), ud = fpu.unpackd.bind(fpu), ug = fpu.unpackg.bind(fpu);
        const shift1 = (r) => {                                  /* CHANGED: one guard bit short */
            r.lo = ((r.lo >>> 1) | (r.hi << 31)) >>> 0;
            r.hi = (r.hi >>> 1) >>> 0;
        };
        fpu.unpackf = function(hi, r) { uf(hi, r); shift1(r); };
        fpu.unpackd = function(hi, lo, r) { ud(hi, lo, r); shift1(r); };
        fpu.unpackg = function(hi, lo, r) { ug(hi, lo, r); shift1(r); };
        return;
    }

    case "resopSilent":
    case "ovflSilent":
    case "unflSilent": {
        /*
         * Swallow one fault class.  The shipped routines call this.fault() from the middle of a
         * statement sequence and rely on it not returning, so a fault that returns falls through
         * into the "it was a zero" / "pack it anyway" path -- which is exactly the shape of the
         * real defect each of these names.
         */
        fpu.fault = function(code, p1 = 0) {
            if (name == "resopSilent" && code == VAXFAULT.RESOP) return 0;
            if (name == "ovflSilent" && code == ABORT_ARITH && p1 == FLT_OVRFLO) return 0;
            if (name == "unflSilent" && code == ABORT_ARITH && p1 == FLT_UNDFLO) return 0;
            throw new VAXFault(code, p1);
        };
        return;
    }

    case "mulNoCross": {
        let orig = fpu.vaxFmul.bind(fpu);
        fpu.vaxFmul = function(a, b, qd, bias, mhi, mlo) {
            return orig(a, b, false, bias, mhi, mlo);            /* CHANGED: qd forced false */
        };
        return;
    }

    case "divPrecF":
        fpu.opDivf = function(opnd) {
            let a = this.ua, b = this.ub;
            this.unpackf(opnd[0], a);
            this.unpackf(opnd[1], b);
            this.vaxFdiv(a, b, 25, 0x80);                        /* CHANGED: was 26 */
            return this.rpackfd(b, false);
        };
        return;

    case "addNoCarryNorm":
        fpu.vaxFadd = function(a, b, mhi, mlo) {
            if ((a.hi == 0) && (a.lo == 0)) { a.copyFrom(b); return; }
            if ((b.hi == 0) && (b.lo == 0)) return;
            if ((a.exp < b.exp) || ((a.exp == b.exp) && (dpCmpT(a, b) < 0))) a.swapWith(b);
            let ediff = a.exp - b.exp;
            if (a.sign ^ b.sign) {
                if (ediff) { dpNegT(b); dpRshST(b, ediff, 1); dpAddT(a, b); }
                else dpSubT(a, b);
                a.hi = (a.hi & ~mhi) >>> 0;
                a.lo = (a.lo & ~mlo) >>> 0;
                this.norm(a);
            } else {
                if (ediff) dpRshT(b, ediff);
                dpAddT(a, b);
                /* CHANGED: the carry-out renormalize is gone */
                a.hi = (a.hi & ~mhi) >>> 0;
                a.lo = (a.lo & ~mlo) >>> 0;
            }
        };
        return;

    case "writeQNoProbe":
        fpu.writeQ = function(rl, rh) {
            let cpu = this.cpu, d = cpu.decoder;
            if (d.spec > (0x050 | 15)) {
                let wa = cpu.acc << 4;
                cpu.mmu.writeData(d.va, rl, 4, wa);              /* CHANGED: no Test(va+7) probe */
                cpu.mmu.writeData((d.va + 4) | 0, rh, 4, wa);
            } else {
                if (d.rn >= 14) this.fault(VAXFAULT.RESAD);
                cpu.regs[d.rn] = rl;
                cpu.regs[d.rn + 1] = rh;
            }
        };
        return;

    default:
        throw new Error("unknown mutation " + name);
    }
}

const PRISTINE = {
    F_ROUND: VAXFloat.F_ROUND, D_ROUND: VAXFloat.D_ROUND, G_ROUND: VAXFloat.G_ROUND,
    NORMTAB: VAXFloat.NORMTAB, NORMMASK: VAXFloat.NORMMASK, MAXV: VAXFloat.MAXV
};

/**
 * restoreMutations()
 */
function restoreMutations()
{
    for (let k of Object.keys(PRISTINE)) VAXFloat[k] = PRISTINE[k];
}

/* ------------------------------------------------------------------------------------------- *
 * main
 * ------------------------------------------------------------------------------------------- */

/**
 * main()
 */
async function main()
{
    let argv = process.argv.slice(2);
    const getArg = (name, dflt) => {
        let i = argv.indexOf(name);
        return (i >= 0 && i + 1 < argv.length)? argv[i + 1] : dflt;
    };
    let simhBin = findSimh(getArg("--simh", null));
    let nCases = +getArg("--cases", DEFAULT_CASES);
    let seed = +getArg("--seed", 20260726);
    let fSelfcheck = argv.indexOf("--selfcheck") >= 0;
    let fSkipEhkaa = argv.indexOf("--skip-ehkaa") >= 0;
    let scratch = fs.mkdtempSync(path.join(os.tmpdir(), "fpadiff-"));
    let opts = {
        trace: getArg("--trace", null),
        ehkaaExe: getArg("--ehkaa", findEhkaa())
    };

    console.log("fpadiff: SIMH " + simhBin);

    /* Every exit path -- requireFpSupport() throwing, a --selfcheck failure, an undersized-args
       FAIL, a normal FAIL/PASS, or any other thrown exception -- runs through this try/finally,
       so scratch is always removed.  HANDOFF.md pcjsvax-bd1: an earlier revision called
       process.exit() from three separate places without removing scratch first, and
       requireFpSupport() throwing (e.g. no FP-patched SIMH) skipped the two rmSync() calls that
       only ran on paths that got that far. */
    try {
    let problems = [];
    requireFpSupport(simhBin, scratch);

    if (fSelfcheck) {
        /*
         * Each mutation gets a short exerciser pass plus the QUADSTORE phase, because two of them
         * (writeQNoProbe, and any that changes a stored value) are only visible in one of the two.
         */
        console.log("selfcheck: " + MUTATIONS.length + " mutations\n");
        let nMissed = 0;
        for (let mut of MUTATIONS) {
            restoreMutations();
            let caught = 0, detail = "";
            let e1 = runExerciser(simhBin, 4000, seed, mut, scratch, true);
            caught += e1.failures.length;
            if (e1.failures.length) detail = e1.failures[0];
            if (!caught) {
                let e2 = runQuadStore(simhBin, seed, mut, scratch);
                caught += e2.failures.length;
                if (e2.failures.length) detail = "[quadstore] " + e2.failures[0];
            }
            restoreMutations();
            if (caught) {
                console.log("  CAUGHT  " + mut.padEnd(16) + " " + caught + " failure(s): " +
                    detail.slice(0, 110));
            } else {
                console.log("  MISSED  " + mut.padEnd(16) + " the differential did not notice");
                nMissed++;
            }
        }
        restoreMutations();
        if (nMissed) {
            console.log("\nFAIL: " + nMissed + " mutation(s) survived.  An undetected mutation is a" +
                " HOLE IN THE ORACLE and must be investigated, not papered over with more cases.");
            process.exitCode = 1;
            return;
        }
        console.log("\nselfcheck PASS: every mutation was caught");
        return;
    }

    if (nCases < MIN_CASES) {
        console.error("FAIL: --cases " + nCases + " is below the floor of " + MIN_CASES +
            ".  The coverage floors below are absolute counts and are NOT scaled down with the" +
            " case count: an undersized run must fail, not quietly pass.");
        process.exitCode = 1;
        return;
    }

    /* ---------------------------------------------------------------- EXERCISER */
    let ex = runExerciser(simhBin, nCases, seed, "", scratch, false);
    let s = ex.stats;
    console.log("\nEXERCISER");
    console.log("  cases                  " + s.nCases);
    console.log("  compared identical     " + s.nCompared);
    console.log("  completed / faulted    " + s.nOK + " / " + s.nFaulted);
    console.log("  memory dests / sweep   " + s.nMem + " / " + s.nSweep +
        " longwords, " + s.nSweepChanged + " written");
    console.log("  non-trivial results    " + s.nNonTrivial + " of " + s.nResultChecks +
        " (" + (s.nResultChecks? (100 * s.nNonTrivial / s.nResultChecks).toFixed(1) : "0") + "%)");
    let clsLine = [];
    for (let [k, v] of s.cls) clsLine.push(k + "=" + v);
    console.log("  classes                " + clsLine.join(" "));
    for (let f of ex.failures) problems.push("EXERCISER: " + f);

    for (let op of OPS) {
        let n = s.byOpcode.get(op.opc) || 0;
        if (n < FLOORS.perOpcode) {
            problems.push("COVERAGE: " + op.name + " ran " + n + " times, floor is " + FLOORS.perOpcode);
        }
    }
    if (s.nFaulted < FLOORS.faulted) {
        problems.push("COVERAGE: only " + s.nFaulted + " case(s) faulted, floor is " +
            FLOORS.faulted + " -- the fault paths are half of what this item is for");
    }
    for (let k of Object.keys(FLOORS)) {
        if (k == "perOpcode" || k == "nonTrivial" || k == "faulted") continue;
        let n = s.cls.get(k) || 0;
        if (n < FLOORS[k]) {
            problems.push("COVERAGE: class '" + k + "' occurred " + n + " times, floor is " + FLOORS[k]);
        }
    }
    let ratio = s.nResultChecks? (s.nNonTrivial / s.nResultChecks) : 0;
    if (ratio < FLOORS.nonTrivial) {
        problems.push("COVERAGE: only " + (100 * ratio).toFixed(1) + "% of stored results were" +
            " non-trivial, floor is " + (100 * FLOORS.nonTrivial) + "% -- a run whose answers are" +
            " mostly zero or the first operand unchanged has not tested the arithmetic");
    }
    if (s.nCompared != s.nCases) {
        problems.push("EXERCISER: " + (s.nCases - s.nCompared) + " case(s) did not compare clean");
    }

    /* ---------------------------------------------------------------- QUADSTORE */
    let qs = runQuadStore(simhBin, seed, "", scratch);
    let q = qs.stats;
    console.log("\nQUADSTORE (WRITE_Q cross-page probe, MAPEN on)");
    console.log("  cases                  " + q.nCases +
        " (" + q.nStraddle + " straddling a page boundary, " + q.nUnaligned + " unaligned)");
    console.log("  completed / faulted    " + q.nOK + " / " + q.nFaulted);
    console.log("  longwords changed      " + q.nWritten);
    for (let f of qs.failures) problems.push("QUADSTORE: " + f);
    if (q.nCases < MIN_QUAD_CASES) {
        problems.push("COVERAGE: QUADSTORE ran " + q.nCases + " cases, floor is " + MIN_QUAD_CASES);
    }
    if (q.nFaulted < MIN_QUAD_FAULTS) {
        problems.push("COVERAGE: QUADSTORE saw only " + q.nFaulted + " faults, floor is " +
            MIN_QUAD_FAULTS + " -- the phase exists to grade the fault path");
    }
    if (q.nWritten == 0) {
        problems.push("COVERAGE: QUADSTORE wrote nothing at all; the sweep proves nothing");
    }

    /* ---------------------------------------------------------------- EHKAA */
    if (!fSkipEhkaa) {
        let eh = runEhkaa(simhBin, opts, "", scratch);
        let e = eh.stats;
        console.log("\nEHKAA (real workload)");
        console.log("  instructions in trace  " + e.nTotal);
        console.log("  F/D/G instructions     " + e.nFp);
        console.log("  replayed / faulted     " + e.nReplayed + " / " + e.nFaulted);
        console.log("  graded in situ         " + e.nInSitu);
        let names = [...e.byOpcode.entries()].sort((a, b) => b[1] - a[1])
            .map(([n, c]) => n + "=" + c);
        console.log("  opcodes                " + names.join(" "));
        for (let f of eh.failures) problems.push("EHKAA: " + f);
        if (e.nReplayed != e.nFp) {
            problems.push("EHKAA: found " + e.nFp + " F/D/G instructions but replayed only " +
                e.nReplayed + " -- cases were dropped");
        }
        if (e.nFp < MIN_EHKAA_FP) {
            problems.push("COVERAGE: EHKAA yielded only " + e.nFp + " F/D/G instructions, floor is " +
                MIN_EHKAA_FP + " -- a truncated capture proves nothing");
        }
        if (e.nInSitu < MIN_EHKAA_INSITU) {
            problems.push("COVERAGE: only " + e.nInSitu + " EHKAA results were graded against the" +
                " diagnostic's own printed result, floor is " + MIN_EHKAA_INSITU);
        }
    } else {
        console.log("\nEHKAA skipped (--skip-ehkaa)");
    }

    console.log("");
    if (problems.length) {
        for (let p of problems.slice(0, 40)) console.log("  " + p);
        if (problems.length > 40) console.log("  ... and " + (problems.length - 40) + " more");
        console.log("\nFAIL (" + problems.length + " problem(s))");
        process.exitCode = 1;
        return;
    }
    console.log("PASS");
    } finally {
        fs.rmSync(scratch, {recursive: true, force: true});
    }
}

if (process.argv[1] && path.resolve(process.argv[1]) == path.resolve(fileURLToPath(import.meta.url))) {
    main().catch((e) => { console.error(e); process.exitCode = 1; });
}

export {
    runExerciser, runEhkaa, runQuadStore, genCases, applyMutation, restoreMutations,
    makeMachine, runCase, findSimh, hex, mkF, mkD, mkG, MUTATIONS, OPS, FLOORS
};
